abrasion <- c(14,14,12,10,13,14,11,9,17,8,12,13, 13,13,9,11) 
brand <- as.factor(rep(c("A", "B", "c", "D"),4)) 
tire <- data.frame(abrasion, brand) 
car=as.factor(rep(1:4,each=4))
abrasion.aov <- aov(abrasion ~ brand, data = tire) 
summary(abrasion.aov) 
abrasion.glm <- glm(abrasion ~ brand, data = tire) 
summary(abrasion.glm) 
boxplot(abrasion ~ brand, data=tire)